---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	manage_memory(manage_memory)
	router(router)
	pull_trends(pull_trends)
	pull_shopping(pull_shopping)
	pull_news(pull_news)
	pull_amazon(pull_amazon)
	agent(agent)
	tools(tools)
	remember(remember)
	__end__([<p>__end__</p>]):::last
	__start__ --> manage_memory;
	agent -.-> remember;
	agent -.-> tools;
	manage_memory --> router;
	pull_amazon --> agent;
	pull_news --> agent;
	pull_shopping --> agent;
	pull_trends --> agent;
	router -.-> agent;
	router -.-> pull_amazon;
	router -.-> pull_news;
	router -.-> pull_shopping;
	router -.-> pull_trends;
	tools --> agent;
	remember --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
